
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

drive_wheels:
  type: "velocity_controllers/JointGroupVelocityController"
  joints: 
  - right_wheel_joint 
  - left_wheel_joint 
  # - steering_wheel_joint
  pid: # Required because we're controlling a velocity interface
    kp: 1.0
    ki: 0
    kd: 0
    right_wheel_joint: {p: kp, i: ki, d: kd} 
    left_wheel_joint: {p: kp, i: ki, d: kd} 
     


steering_axel:
  type: "velocity_controllers/JointPositionController"
  joint: steering_joint
  pid: {p: 7, i: 4, d: 0}

steering_wheel:
  type: "velocity_controllers/JointPositionController"
  joint: steering_wheel_joint
  pid: {p: 0, i: 0, d: 0}



fork_joint_controller:
  type: "position_controllers/JointPositionController"
  joint: fork_joint
  pid: {p: 7, i: 4, d: 0}




  