
joint_limits:
  right_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 18.0

  left_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 18.0

  steering_joint:
    has_position_limits: true
    min_position: 1.57
    max_position: -1.57
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: true
    max_acceleration: 100.0
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 20.0

  steering_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: true
    max_acceleration: 50.0
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 0.001
 
  fork_joint:
    has_position_limits: true
    min_position: 0
    max_position: 0.3
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    has_jerk_limits: false
    has_effort_limits: true
    
